version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - dapr-network

  service-a:
    image: service-a:latest
    container_name: service-a
    build:
      context: ./service-a
    ports:
      - "5001:5001"
    networks:
      - dapr-network
    environment:
      - DAPR_HTTP_PORT=3500
      - DAPR_GRPC_PORT=50001
      - APP_ID=service-a
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5001/actuator/health" ]
      interval: 10s
      timeout: 10s
      retries: 10

  service-a-dapr:
    image: daprio/daprd:latest
    container_name: service-a-dapr
    command: [
      "./daprd",
      "--app-id", "service-a",
      "--app-port", "5001",
      "--app-channel-address", "service-a",
      "--dapr-http-port", "3500",
      "--dapr-grpc-port", "50001",
      "--enable-metrics"
    ]
    depends_on:
      service-a:
        condition: service_healthy
    networks:
      - dapr-network
    environment:
      - DAPR_INSECURE=true
      - DAPR_LOG_LEVEL=debug
    ports:
      - "3500:3500"
      - "50001:50001"
    expose:
      - "3500"
      - "50001"

  service-b:
    image: service-b:latest
    container_name: service-b
    build:
      context: ./service-b
    ports:
      - "5002:5002"
    networks:
      - dapr-network
    environment:
      - DAPR_HTTP_PORT=3501
      - DAPR_GRPC_PORT=50002
      - APP_ID=service-b
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5002/actuator/health" ]
      interval: 10s
      timeout: 10s
      retries: 10
    depends_on:
      mysql:
        condition: service_healthy

  service-b-dapr:
    image: daprio/daprd:latest
    container_name: service-b-dapr
    command: [
      "./daprd",
      "--app-id", "service-b",
      "--app-port", "5002",
      "--app-channel-address", "service-b",
      "--dapr-http-port", "3501",
      "--dapr-grpc-port", "50002",
      "--enable-metrics"
    ]
    depends_on:
      - service-b
    networks:
      - dapr-network
    environment:
      - DAPR_INSECURE=true
      - DAPR_LOG_LEVEL=debug
    ports:
      - "3501:3501"
      - "50002:50002"

volumes:
  mysql-data:

networks:
  dapr-network:
    driver: bridge