spring.application.name=service-a
server.port=5001
#serviceb.url=http://localhost:5002/ping
serviceb.app-id=service-b
serviceb.method=/service-b/ping

# Resilience4j Circuit Breaker Configuration
resilience4j.circuitbreaker.instances.serviceB.slidingWindowSize=10
resilience4j.circuitbreaker.instances.serviceB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.serviceB.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.serviceB.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.serviceB.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.serviceB.recordExceptions=java.net.ConnectException,java.net.SocketTimeoutException
resilience4j.circuitbreaker.instances.serviceB.ignoreExceptions=java.lang.IllegalArgumentException